version: 1
orders/received:
  url: http://lab6a.eastus2.cloudapp.azure.com/storage/orders/received
parts/damaged:
  url: http://lab6a.eastus2.cloudapp.azure.com/storage/parts/damaged

events:
  hostname: lab6a.eastus2.cloudapp.azure.com
  port: 9092
  topic: events